<?xml version="1.0" encoding="utf-8"?><Database Name="ShiftsManagerDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localDb)\localDB;Initial Catalog=ShiftsManagerDB;Integrated Security=True" SettingsObjectName="ShiftsManagerSystem.Properties.Settings" SettingsPropertyName="ShiftsManagerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="userRate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="isClockedIn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="totalMinutes" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="User_Shift" Member="Shifts" ThisKey="userID" OtherKey="userID" Type="Shift" />
      <Association Name="User_Payment" Member="Payments" ThisKey="userID" OtherKey="userID" Type="Payment" />
    </Type>
  </Table>
  <Table Name="dbo.Shifts" Member="Shifts">
    <Type Name="Shift">
      <Column Name="shiftID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="shiftClockIn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="shiftClockOut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Shift" Member="User" ThisKey="userID" OtherKey="userID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payments" Member="Payments">
    <Type Name="Payment">
      <Column Name="paymentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="paymentAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="paymentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Payment" Member="User" ThisKey="userID" OtherKey="userID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>